remote_theme: just-the-docs/just-the-docs

title: FFXIV Elemental Raid Macros

color_scheme: dark

back_to_top: true
back_to_top_text: "Back to top"

footer_content: Final Fantasy XIV Elemental DC Raid Macros


defaults:
  -
    scope:
      path: "/README.md/"
    values:
      title: Home
      nav_order: 1
      permalink: /
  -
    scope:
      path: "/6.0_endwalker/README.md/"
    values:
      title: 6.0 Endwalker
      nav_order: 2
      has_children: true
      permalink: /6.0_endwalker/
  -
    scope:
      path: "/6.0_endwalker/ex_zodiark/README.md/"
    values:
      title: Zodiark EX
      parent: 6.0 Endwalker
      nav_order: 1
      permalink: /6.0_endwalker/ex_zodiark/
  -
    scope:
      path: "/6.0_endwalker/ex_hydaelyn/README.md/"
    values:
      title: Hydaelyn EX
      parent: 6.0 Endwalker
      nav_order: 2
      permalink: /6.0_endwalker/ex_hydaelyn/
  -
    scope:
      path: "/6.0_endwalker/ex_endsinger/README.md/"
    values:
      title: Meteion EX
      parent: 6.0 Endwalker
      nav_order: 3
      permalink: /6.0_endwalker/ex_endsinger/
  -
    scope:
      path: "/6.0_endwalker/p1s/README.md/"
    values:
      title: P1S
      parent: 6.0 Endwalker
      permalink: /6.0_endwalker/p1s/
  -
    scope:
      path: "/6.0_endwalker/p2s/README.md/"
    values:
      title: P2S
      parent: 6.0 Endwalker
      permalink: /6.0_endwalker/p2s/
  -
    scope:
      path: "/6.0_endwalker/p3s/README.md/"
    values:
      title: P3S
      parent: 6.0 Endwalker
      permalink: /6.0_endwalker/p3s/
  -
    scope:
      path: "/6.0_endwalker/p4s_1/README.md/"
    values:
      title: P4S P1
      parent: 6.0 Endwalker
      permalink: /6.0_endwalker/p4s_1/
  -
    scope:
      path: "/6.0_endwalker/p4s_2/README.md/"
    values:
      title: P4S P2
      parent: 6.0 Endwalker
      permalink: /6.0_endwalker/p4s_2/
  -
    scope:
      path: "/ultimates/README.md/"
    values:
      title: Ultimates
      nav_order: 3
      has_children: true
      permalink: /ultimates/
  -
    scope:
      path: "/ultimates/ucob/README.md/"
    values:
      title: UCoB
      parent: Ultimates
      nav_order: 1
      permalink: /ultimates/ucob/
  -
    scope:
      path: "/ultimates/uwu/README.md/"
    values:
      title: UWU
      parent: Ultimates
      nav_order: 2
      permalink: /ultimates/uwu/
  -
    scope:
      path: "/ultimates/tea/README.md/"
    values:
      title: TEA
      parent: Ultimates
      nav_order: 3
      has_children: true
      permalink: /ultimates/tea/
  -
    scope:
      path: "/ultimates/tea/en/01_living_liquid.md/"
    values:
      title: 1. Living Liquid
      parent: TEA
      grand_parent: Ultimates
  -
    scope:
      path: "/ultimates/tea/en/02_limit_cut_1211.md/"
    values:
      title: 2. Limit Cut (1211)
      parent: TEA
      grand_parent: Ultimates
  -
    scope:
      path: "/ultimates/tea/en/02_limit_cut_1256.md/"
    values:
      title: 2. Limit Cut (1256)
      parent: TEA
      grand_parent: Ultimates
  -
    scope:
      path: "/ultimates/tea/en/03_bjcc.md/"
    values:
      title: 3. Brute Justice + Cruise Chaser
      parent: TEA
      grand_parent: Ultimates
  -
    scope:
      path: "/ultimates/tea/en/04_alex_prime.md/"
    values:
      title: 4. Alexander Prime
      parent: TEA
      grand_parent: Ultimates
  -
    scope:
      path: "/ultimates/tea/en/05_perfect_alex.md/"
    values:
      title: 5. Perfect Alexander
      parent: TEA
      grand_parent: Ultimates