remote_theme: just-the-docs/just-the-docs

title: FFXIV Elemental Raid Macros

color_scheme: dark

back_to_top: true
back_to_top_text: "Back to top"

defaults:
  -
    scope:
      path: "/6.0_endwalker/p4s_2/README.html"
    values:
      title: P4S P2
      parent: 6.0 Endwalker
      permalink: /6.0_endwalker/p4s_2/