name: Markdown Links Check

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Runs every Monday at 9am
  schedule:
    - cron: "0 9 * * 1"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # checks all markdown files including all subfolders
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/markdown-links-config.json'
